### ISSUE TITLE
won't run

### ISSUE THREAD

**Issue by rimthekid** [therealbluepandabear/PyxlMoose#41]
**Describe the bug**
the log is down below.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
``2022-02-11 09:37:18.733 12671-12671/com.realtomjoney.pyxlmoose E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.realtomjoney.pyxlmoose, PID: 12671
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.realtomjoney.pyxlmoose/com.realtomjoney.pyxlmoose.activities.main.MainActivity}: android.view.InflateException: Binary XML file line #36 in com.realtomjoney.pyxlmoose:layout/activity_main: Binary XML file line #36 in com.realtomjoney.pyxlmoose:layout/activity_main: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3340)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
     Caused by: android.view.InflateException: Binary XML file line #36 in com.realtomjoney.pyxlmoose:layout/activity_main: Binary XML file line #36 in com.realtomjoney.pyxlmoose:layout/activity_main: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
     Caused by: android.view.InflateException: Binary XML file line #36 in com.realtomjoney.pyxlmoose:layout/activity_main: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1014)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1144)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1105)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.realtomjoney.pyxlmoose.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:68)
        at com.realtomjoney.pyxlmoose.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:62)
        at com.realtomjoney.pyxlmoose.activities.main.MainActivity_setBindingsKt.setBindings(MainActivity+setBindings.kt:6)
        at com.realtomjoney.pyxlmoose.activities.main.MainActivity.onCreate(MainActivity.kt:23)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3315)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
2022-02-11 09:37:18.733 12671-12671/com.realtomjoney.pyxlmoose E/AndroidRuntime: Caused by: java.lang.IllegalArgumentException: This component requires that you specify a valid TextAppearance attribute. Update your app theme to inherit from Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTextAppearance(ThemeEnforcement.java:185)
        at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:116)
        at com.google.android.material.navigation.NavigationBarView.<init>(NavigationBarView.java:149)
        at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:108)
        at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:103)
        at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:98)
        	... 28 more
2022-02-11 09:37:18.770 12671-12671/com.realtomjoney.pyxlmoose I/Process: Sending signal. PID: 12671 SIG: 9
``

**Comment by therealbluepandabear** [comment]
Hey,

You would probably need to give me more information as to how I can reproduce this error instead of just an exception message.

**If you want my Discord is theandroiddevguy123#9011 - we can discuss this more.**

You might want to:

- Try updating the project.
- Opening and closing the app.

Cheers,
thebluepandabear

**Comment by rimthekid** [comment]
this happened when I  tried to open the app!

**Comment by rimthekid** [comment]
Don't you have a matrix account?

**Comment by therealbluepandabear** [comment]
Yeah I do, my name is: _@therealbluepandabear:matrix.org_
